animusdev/whiTGreen

- code/game/objects/structures/signs.dm
случайно не туда бранч, ну да пофигу, тут все равно кода нет
Тикет #40
> Я в портретах

- code/game/gamemodes/nuclear/nuclearbomb.dm
Теперь он имеет список допустимых зетуровней (который сейчас совпадает с тем, что было раньше), который расширяется по всем этажам оных зетуровней, так что диск больше не исчезает, если его уронить в подвал.
#91
> Апгрейд нюкодиска.

- code/modules/admin/create_object.dm
- html/create_object.html
Теперь он не выводит дерево объектов до первого поиска, и до кучи хранит экземпляры страниц для быстрого спавна заместо генерации новой каждый раз.
> Подкрутил спавн объектов.

- code/modules/mob/living/simple_animal/hostile/syndicate.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- html/create_object.html
Опера синдикота теперь уязвимы к пулям и к ударам в ближнем бою, у симплэнималов проверка на недамажность теперь идет ПОСЛЕ проверки на то, является ли это медициной.
Ну и ебучий хтмл файл, который вроде ранее антрекнутый был и я неверно оный впихнул в прошлый ПР, который внезапно решил, что я в нем стер часть (которую я и добавил вторым коммитом).
> Порция фиксов.

- code/modules/admin/verbs/adminpm.dm
- code/world.dm
* Now command !who displays total players
* Now command !ah  plays a sound for player
* Now all AHelp messages sends do Discord
* Hell yeah!
> Some bot changes.

- code/_onclick/drag_drop.dm
- code/game/atoms_movable.dm
- code/game/objects/items.dm
- code/game/objects/items/robot/robot_storage.dm
- code/game/objects/items/weapons/storage/storage.dm
- code/modules/mob/living/silicon/robot/inventory.dm
Должно уменьшить количество ложных срабатываний, заодно выпилены лишние проверки.
Солвит  #124.
Сейчас еще для #95 накожу дополнение (не мержте пока).
> Изменение обработки драгНдропа на айтемах и впринципе.

- code/game/turfs/simulated/floor/salty.dm
Добавил в аргументы вызова прока невывод прогрессбаров и независимость от занятости рук.
> Фикс соляных прогрессбаров.

- code/modules/mob/dead/observer/observer.dm
Должно исправить траблы с следованием из обсерва.
> Быстрофикс следования.

- code/game/gamemodes/the_thing/powers/regeneration.dm
- code/game/gamemodes/the_thing/powers/separation.dm
- code/game/gamemodes/the_thing/the_thing.dm
- code/modules/mob/living/simple_animal/the_thing/the_thing.dm
> SomeTHING fix

- code/__HELPERS/text.dm
Не уверен, откуда оно начало копипаститься, но что на вайтотг, что тут - ошибка одна и та же.
Пофиксил, по идее теперь всякий ООЦ и ИЦ будет корректно санитайзиться.
> Фикс рхтмля.

- code/modules/admin/admin_ranks.dm
- code/modules/admin/admin_verbs.dm
- code/modules/client/client procs.dm
Не уверен, ибо лень у себя поднимать БД. Но по идее, если не накосячил, должно теперь нормально работать (при реконнекте будет выдаваться реадмин верб, при реадмине будет реадминить только одного).
> Вродефикс реадмина.

- code/__DEFINES/misc.dm
- code/game/atoms.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/tiles/tile_mineral.dm
- code/game/objects/items/stacks/tiles/tile_types.dm
- code/game/objects/structures/false_walls.dm
- code/game/objects/structures/mineral_doors.dm
- code/game/objects/structures/statues.dm
- code/game/turfs/simulated/floor/mineral_floor.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/simulated/walls_mineral.dm
- code/game/turfs/turf.dm
- code/modules/mining/mine_turfs.dm
- code/modules/mining/ores_coins.dm
- code/modules/mob/living/living_defense.dm
Выкладываю пока что для возможного обнаружения косяков и предложений по балансу (числа вообще с потолка взял, но вроде не сильно лютым получилось). Компилится, но пока рабочесть не проверял.
Излучение с урана перепихнуто на обогащенный уран и изделия из него, изменена механика излучения, скоро будет еще всякое разное.
> Реворк радиации.

- code/modules/mob/living/simple_animal/the_thing/the_thing.dm
Мелкие бьют слабее, все из них огребают в два раза сильнее от температурного урона.
> Нерфы тентаклемонстров

- code/modules/research/designs/autolathe_designs.dm
Все равно ведь я тут один коммичу, буду сразу в мастер ПРы кидать.
> Резина в автолат

- code/world.dm
Не знаю, почему оно до сих пор было так, но так оно выбивается из общего строя (и мне лень переделывать бота на вот это исключение).
> Небольшое исправление того же ворлдтопика.

- code/LINDA/LINDA_fire.dm
- code/controllers/subsystem/multiz.dm
- code/game/gamemodes/nuclear/nuclearbomb.dm
- code/game/turfs/space/space.dm
- code/game/turfs/turf.dm
- code/modules/awaymissions/maploader/reader.dm
- code/modules/multiz/controller.dm
- code/modules/multiz/turf.dm
- tgstation.dme
По сути должна повыситься скорость обработки и скорость обновления.
> Перепил мз контроллеров и не только.

- .travis.yml
- code/controllers/subsystem/multiz.dm
- code/modules/multiz/controller.dm
- code/modules/multiz/turf.dm
- code/world.dm
> Исправления крашей мзконтроллера и тестзапуск в травис.

- code/__DEFINES/misc.dm
- code/game/atoms.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/tiles/tile_mineral.dm
- code/game/objects/items/stacks/tiles/tile_types.dm
- code/game/objects/structures/false_walls.dm
- code/game/objects/structures/mineral_doors.dm
- code/game/objects/structures/statues.dm
- code/game/turfs/simulated/floor/mineral_floor.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/simulated/walls_mineral.dm
- code/game/turfs/turf.dm
- code/modules/mining/mine_turfs.dm
- code/modules/mining/ores_coins.dm
- code/modules/mob/living/living_defense.dm
Ибо первое дисбалансно, а второе сыро и лагообразующе, к тому же не востребованно.
> Реверт архитектоправок и переработки радиации.

- code/modules/multiz/turf.dm
- code/modules/webhook/webhook.dm
Пофиксил спам рантаймами от опенспейсов, выпилил "защиту" от слапов из вебхуков. Последнее затем, что лучше санитайзить слапы, чем игнорировать сообщения с ними.
> Мелкие исправления.

- code/game/verbs/ooc.dm
- code/modules/webhook/webhook.dm
- code/world.dm
> probably fixes manifest categoring and adds bot_token verb

- code/game/verbs/who.dm
- code/world.dm
Какая-то хрень произошла и в списке админов оказался нулловый клиент, который пиздец рантаймил. Эта штука должна фиксить последствия подобной хрени.
> horrible bug fix

- code/world.dm
> Небольшие изменения команд бота.

- code/modules/projectiles/firing.dm
- code/modules/projectiles/guns/energy/special.dm
Фиксит багование неавтоматического оружия на сверхмощную стрельбу.
> yet another game breaking bugfix

- code/game/gamemodes/the_thing/powers/separation.dm
> Фикс проебанной жизни

- code/ATMOSPHERICS/components/trinary_devices/filter.dm
- code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
- code/game/machinery/pipe/construction.dm
- code/game/objects/items/weapons/RPD.dm
Фиксит счетчик в РПД, слетающее состояние тринарных труб при флипе-прикручивании-откручивании, вроде фиксит кривое поведение установленных игроками тринарных труб.
И заодно выпиливает магические константы из кода, где я рылся.
Дебаговый вывод забыл убрать, но ща уберу.
> Ебался полдня, заебался.

- code/__HELPERS/_logging.dm
- code/controllers/subsystem/shuttles.dm
- code/controllers/subsystem/shuttles/emergency.dm
- code/game/gamemodes/changeling/powers/strained_muscles.dm
- code/game/verbs/reimu_hakkureis_donations.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/webhook/webhook.dm
- code/world.dm
- html/changelog.html
Падения и пиздюли тупыми предметами (по телу или голове) и кулаками теперь вероятностно сносят шапку с башни (некоторые шапки, вроде шлемов скафандров, устойчивы к этому ибо хорошо сидят на башне).
Поправил трость в донатпанели (ее путь поменялся) и добавил фейковые робу и шапку марисы (согласно реквесту ребы через алекса).
Перепилил напряженные мышцы гены, исправив одну проблему, связанную с условием выхода из цикла, и перекинув цикл в отдельный прок, чтобы только один инстанс на моба крутился за раз. Возможно, пофиксит фантомный баг с истощением ген через эту способность.
> Время охуительных фич.

- code/game/gamemodes/wizard/soulstone.dm
- code/game/mecha/combat/combat.dm
- code/game/mecha/equipment/tools/medical_tools.dm
- code/game/mecha/mech_fabricator.dm
- code/game/mecha/mecha.dm
- code/game/mecha/mecha_control_console.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/lighting/lighting_system.dm
- code/orphaned procs/dbcore.dm
Почему эти черти не могут выкатить какой-нибудь список, куда добавляют зарезервированные слова?
> Retarded bug fix
